/*
  Warnings:

  - You are about to alter the column `id` on the `Todo` table. The data in that column will be cast from `BigInt` to `Int`. This cast may fail. Please make sure the data in the column can be cast.

*/
-- RedefineTables
CREATE TABLE "_prisma_new_Todo" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "content" STRING,

    CONSTRAINT "Todo_pkey" PRIMARY KEY ("id")
);
INSERT INTO "_prisma_new_Todo" ("content","createdAt","id","updatedAt") SELECT "content","createdAt","id","updatedAt" FROM "Todo";
DROP TABLE "Todo" CASCADE;
ALTER TABLE "_prisma_new_Todo" RENAME TO "Todo";
